services:

  mariadb:
    image: mariadb:11
    environment:
      - MARIADB_DATABASE=airsonicdb
      - MARIADB_USER=airsonic
      - MARIADB_PASSWORD=passwd
      - MARIADB_ROOT_PASSWORD=passwd
    volumes:
      - ./data/mariadb:/var/lib/mysql
    restart: on-failure

  airsonic-pulse:
    depends_on:
      - mariadb
    image: ghcr.io/litebito/airsonic-pulse
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - spring_datasource_url=jdbc:mariadb://mariadb:3306/airsonicdb
      - spring_datasource_username=airsonic
      - spring_datasource_password=passwd
      # - CONTEXT_PATH= #optional
      # - JAVA_OPTS= #optional
    volumes:
      - ./data/airsonic:/var/airsonic
      - ./data/music:/var/music
      - ./data/playlists:/var/playlists
      - ./data/podcasts:/var/podcasts
    ports:
      - 4040:4040 # HTTP
      # - 1900:1900 # DLNA/UPnP
    # devices:
    #   - /dev/snd:/dev/snd #optional
    restart: on-failure
