name: Trivy scan
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "*.txt"
      - ".github/**"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "*.txt"
      - ".github/**"
  schedule:
    - cron: '0 0 * * *'
jobs:
  scan:
    name: scan
    runs-on: [self-hosted, linux, x64, repo-airsonic-pulse]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          timeout: '15m'
          skip-dirs: 'airsonic-main,airsonic-rest-api,airsonic-sonos-api'
        env:
          TRIVY_SKIP_JAVA_DB_UPDATE: 'true'
