name: Trivy scan
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  scan:
    name: "trivy-scan"
    runs-on: [self-hosted, linux, x64, repo-airsonic-pulse]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8 # v0.36.0
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          timeout: '15m'
          skip-dirs: 'airsonic-main,airsonic-rest-api,airsonic-sonos-api'
        env:
          TRIVY_SKIP_JAVA_DB_UPDATE: 'true'
