name: "CI - Push to Main"

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "*.txt"
      - "docs/**"
      - "contrib/**"
      - ".github/**"
      - "!.github/workflows/pm_ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Verify environment
        run: |
          java -version
          mvn --version
          ffmpeg -version
      - name: Create music directory
        run: mkdir -p /tmp/music
      - name: Build and test
        run: mvn clean verify
